<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>scss navbar</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css">
  <link rel="stylesheet" type="text/css" href="../dist/main.css">
</head>
<body>
  <div class="navbar-fixed">
    <nav class="navbar">
      <div class="navbar-container">
        <a href="#" class="navbar-brand">
          Navbar Brand
        </a>

        <span id="navbar-dropdown-toggle" class="navbar-dropdown-toggle-target"></span>
        <ul class="navbar-links" id="navbar-links">
          <li>
            <a href="#navbar-dropdown-toggle" class="navbar-dropdown-toggle">Dropdown</a
            ><ul class="navbar-dropdown">
              <li><a href="#" class="navbar-dropdown-link">Dropdown Link</a></li
              ><li><a href="#" class="navbar-dropdown-link">Dropdown Other Link</a></li
              ><li><a href="#" class="navbar-dropdown-link">Dropdown Another Link</a></li>
            </ul>
          </li
          ><li><a href="#" class="navbar-link">Link</a></li
          ><li><a href="#" class="navbar-link">Other Link</a></li
          ><li><a href="#" class="navbar-link">Another Link</a></li
          ><li><a href="#" class="navbar-featured-link">Featured Link</a></li>
        </ul>

        <a href="#navbar-links" class="navbar-mobile-toggle"></a>
        <a href="#" class="navbar-mobile-close"></a>
      </div>
    </nav>
  </div>

  <div class="md-up-8 md-up-push-2 col">
    <?php for ($i = 0; $i < 20; $i++): ?>
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <?php endfor ?>
  </div>
</body>
</html>
